### ISSUE TITLE
Adding autoreconnect parameter to options

### ISSUE THREAD

**Issue by opravil-jan** [fhemberger/good-logstash#4]
Hi,

can you add this code (", autoConnect: options.autoConnect || true") on line  https://github.com/fhemberger/good-logstash/blob/master/lib/index.js#L64 to enable autoConnect parameter to be passed to library logstash-client. 

Thank you

**Comment by fhemberger** [comment]
Hi, autoconnect is handled automatically, as the option isn't explicitly set to `false`.
`logstash-client` uses [a strict check](https://github.com/purposeindustries/node-logstash-client/blob/master/lib/client.js#L33), so `undefined !== false`.
